function [fitresult, gof] = createFit(Z2)
%CREATEFIT(Z2)
%  Create a fit.
%
%  Data for 'Smoothed Spline Fit' fit:
%      Y Output: Z2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2014 16:32:39


%% Fit: 'Smoothed Spline Fit'.
[xData, yData] = prepareCurveData( [], Z2 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Smoothed Spline Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Z2', 'Smoothed Spline Fit', 'Location', 'NorthEast' );
% Label axes
ylabel( 'Z2' );
grid on


