function [fitresult, gof] = createFit(M1)
%CREATEFIT(M1)
%  Create a fit.
%
%  Data for 'Smoothed Spline Fit' fit:
%      Y Output: M1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2014 15:18:32



% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Smoothed Spline Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'M1', 'Smoothed Spline Fit', 'Location', 'NorthEast' );
% Label axes
ylabel( 'M1' );
grid on


